
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gech
 */
public class pysical_examintion5 extends javax.swing.JFrame {

    /**
     * Creates new form pysical_examintion5
     */
    public pysical_examintion5(String x,String y,String z) {
        initComponents();
        display.setText(x);
          displayp.setText(y);  
          infoid.setText(z);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rgbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mms = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gls = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnm = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        cn7 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        cn8 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        cn9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        cn10 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        cn11 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        cn12 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        cn1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        cn2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        cn3 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        cn4 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        cn5 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        cn6 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        idfs = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        displayp = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        infoid = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("CN 1");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 229, 118, 25));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("CRNIAL NERVIOUS SYTEM");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 186, 290, 25));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText(" CN 3");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 346, 118, 25));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("CRNIAL NERVIOUS SYSTEM");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 182, 240, 25));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("CN 4");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 414, 118, 25));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("CN 6");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 531, 118, 25));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("PATIENT NAME");
        jLabel24.setBounds(10, 60, 140, 29);
        jDesktopPane1.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("centeral nervios SYSTEM(msk)");
        jLabel6.setBounds(240, 0, 360, 40);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("PERVIOUSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(230, 580, 135, 31);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("SKIP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(620, 580, 75, 31);
        jDesktopPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        rgbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rgbtn.setText("REGISTER");
        rgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbtnActionPerformed(evt);
            }
        });
        rgbtn.setBounds(380, 580, 140, 31);
        jDesktopPane1.add(rgbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mms.setColumns(20);
        mms.setRows(5);
        jScrollPane2.setViewportView(mms);

        jScrollPane2.setBounds(760, 90, 324, 50);
        jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("MINIMENTAL SYSTEM");
        jLabel13.setBounds(550, 100, 200, 25);
        jDesktopPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        gls.setColumns(20);
        gls.setRows(5);
        jScrollPane1.setViewportView(gls);

        jScrollPane1.setBounds(210, 100, 324, 50);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("GLASCOMAS SYSTEM");
        jLabel8.setBounds(10, 120, 200, 25);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("CN 2");
        jLabel10.setBounds(20, 260, 118, 25);
        jDesktopPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnm.setBounds(210, 50, 324, 40);
        jDesktopPane1.add(pnm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("CN 12");
        jLabel19.setBounds(620, 520, 118, 25);
        jDesktopPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("CN 11");
        jLabel18.setBounds(620, 460, 118, 25);
        jDesktopPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("CN 10");
        jLabel20.setBounds(620, 400, 118, 30);
        jDesktopPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("CN 9");
        jLabel11.setBounds(620, 330, 118, 25);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("CN 8");
        jLabel12.setBounds(620, 280, 118, 25);
        jDesktopPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("CN 7");
        jLabel15.setBounds(620, 220, 118, 25);
        jDesktopPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn7.setColumns(20);
        cn7.setRows(5);
        jScrollPane8.setViewportView(cn7);

        jScrollPane8.setBounds(750, 210, 324, 50);
        jDesktopPane1.add(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn8.setColumns(20);
        cn8.setRows(5);
        jScrollPane7.setViewportView(cn8);

        jScrollPane7.setBounds(750, 270, 324, 50);
        jDesktopPane1.add(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn9.setColumns(20);
        cn9.setRows(5);
        jScrollPane6.setViewportView(cn9);

        jScrollPane6.setBounds(750, 330, 324, 50);
        jDesktopPane1.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn10.setColumns(20);
        cn10.setRows(5);
        jScrollPane11.setViewportView(cn10);

        jScrollPane11.setBounds(750, 390, 324, 50);
        jDesktopPane1.add(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn11.setColumns(20);
        cn11.setRows(5);
        jScrollPane10.setViewportView(cn11);

        jScrollPane10.setBounds(750, 450, 324, 50);
        jDesktopPane1.add(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn12.setColumns(20);
        cn12.setRows(5);
        jScrollPane9.setViewportView(cn12);

        jScrollPane9.setBounds(750, 510, 324, 50);
        jDesktopPane1.add(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn1.setColumns(20);
        cn1.setRows(5);
        jScrollPane4.setViewportView(cn1);

        jScrollPane4.setBounds(220, 190, 324, 50);
        jDesktopPane1.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn2.setColumns(20);
        cn2.setRows(5);
        jScrollPane5.setViewportView(cn2);

        jScrollPane5.setBounds(220, 250, 324, 50);
        jDesktopPane1.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn3.setColumns(20);
        cn3.setRows(5);
        jScrollPane3.setViewportView(cn3);

        jScrollPane3.setBounds(220, 310, 324, 50);
        jDesktopPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn4.setColumns(20);
        cn4.setRows(5);
        jScrollPane13.setViewportView(cn4);

        jScrollPane13.setBounds(220, 380, 324, 50);
        jDesktopPane1.add(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn5.setColumns(20);
        cn5.setRows(5);
        jScrollPane12.setViewportView(cn5);

        jScrollPane12.setBounds(220, 440, 324, 50);
        jDesktopPane1.add(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cn6.setColumns(20);
        cn6.setRows(5);
        jScrollPane14.setViewportView(cn6);

        jScrollPane14.setBounds(220, 500, 324, 50);
        jDesktopPane1.add(jScrollPane14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("CN 5");
        jLabel23.setBounds(20, 450, 118, 25);
        jDesktopPane1.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        idfs.setBounds(590, 30, 180, 40);
        jDesktopPane1.add(idfs, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("SEARCH FOR UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(790, 30, 170, 40);
        jDesktopPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanel1.setBounds(10, 10, 1080, 620);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1100, 640));
        getContentPane().add(displayp, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 130, 30));
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 120, 30));

        infoid.setText("jLabel1");
        getContentPane().add(infoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 684, 100, 30));

        jMenu1.setText("                      LOGOUT   ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new pysical_examintion4(display.getText(),displayp.getText(),infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         new SUMERY_PAGE(display.getText(),displayp.getText(),infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgbtnActionPerformed

         String glascomas_system=gls.getText();
         String minimental_system=mms.getText();
         String CN1=cn1.getText();
         String CN2=cn2.getText();
         String CN3=cn3.getText();
         String CN4=cn4.getText();
         String CN5=cn5.getText();
         String CN6=cn6.getText();
         String CN7=cn7.getText();
         String CN8=cn8.getText();
         String CN9=cn9.getText();
         String CN10=cn10.getText();
         String CN11=cn11.getText();
         String CN12=cn12.getText();
         String cranial_nervous_system="CN1="+CN1+"\nCN2="+CN2+"\nCN3="+CN3+"\nCN4="+CN4+"\nCN5="+CN5+"\nCN6="+CN6+"\nCN7="+CN7+"\nCN8="+CN8+"\nCN9="+CN9+"\nCN10="+CN10+"\nCN11="+CN11+"\nCN12="+CN12;
//          String cardio_vascular_system="ARTERIO="+arteroi+"\nVENOUS="+venuos;
//        String resparatory_rate="INSPECTION="+inspection+"\nPALPOTION="+palpotion+"\nPERCUTION="+percution+"\nAUSCULTATION="+auscultation;//insp.getText();
        try
            {
                RMIInterface hello=(RMIInterface)
                Naming.lookup("//localhost/clinical");
                
                    System.out.println(hello.examination4(idfs.getText(),rgbtn.getText(),glascomas_system,minimental_system,CN1,CN2,CN3,CN4,CN5,CN6,CN7,CN8,CN9,CN10,CN11,CN12));
                    JOptionPane.showMessageDialog(null, "CONTINUE", 
                                              null,
                                              JOptionPane.PLAIN_MESSAGE);
                     new SUMERY_PAGE(display.getText(),displayp.getText(),infoid.getText()).setVisible(true);
        this.setVisible(false);
                   
            }
               catch(NotBoundException e){
                System.out.println("Clinicalclient not bound exception:" +e);
               // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
            }
            catch(Exception e){
                System.out.println("HelloClient exception:" +e);
            }
       
        
    }//GEN-LAST:event_rgbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1();
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                while (i < c) {
                    infoid.setText(fetch[0]);
                  //  gap.setText(fetch[9]);
                    String x = (fetch[3]);
//                          int len = x.length();
//                            char[] cc = x.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             x = String.valueOf(cc);
                    String y = (fetch[4]);
                    
//                         cc = y.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             y= String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
//                    hd.setText(fetch[11]);
//                   String blood= (fetch[10]);
//                //   blood presure=
//                   String first="";
//                    int length = blood.length();
//        char[] ccx = blood.toCharArray();
//        for (int h = 0; h < 16; h = h + 1) {
//            first = first + ccx[h];
//        }
//                   
//                        bp.setText(first);
//                        
//                              String firsts="";
//        char[] ccxs = blood.toCharArray();
//        for (int h = 16; h < 36; h = h + 1) {
//            firsts = firsts + ccxs[h];
//        }
//                   
//                        rr.setText(firsts);
//                        
//                        
//                          String firstss="";
//        char[] ccxss = blood.toCharArray();
//        for (int h = 36; h < 50; h = h + 1) {
//            firstss = firstss + ccxs[h];
//        }
//                   
//                        pr.setText(firstss);
//                        
//                       String firstsss="";
//        char[] ccxsss = blood.toCharArray();
//        for (int h = 50; h < 64; h = h + 1) {
//            firstsss = firstsss + ccxss[h];
//        }
//                   
//                        tmp.setText(firstsss); 
                        
                    i++;
                }
//                    JOptionPane.showMessageDialog(null, "SUCCESSFULL", 
//                                              null,
//                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                        null,
                        JOptionPane.PLAIN_MESSAGE);
            }
            // }
            infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1(idfs.getText());
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                if(rgbtn.getText().equals("REGISTER"))
                {
                    rgbtn.setText("UPDATE");
                }

                while (i < c) {
                    infoid.setText(fetch[0]);

                     gls.setText(fetch[47]);
                    mms.setText(fetch[48]);
                    
                    cn1.setText(fetch[49]);
                    cn2.setText(fetch[50]);
                    cn3.setText(fetch[51]);
                    cn4.setText(fetch[52]);
                    // tmp.setText(fetch[14]);

                    cn5.setText(fetch[53]);
                    cn6.setText(fetch[54]);
                    cn7.setText(fetch[55]);
                    cn8.setText(fetch[56]);
                    
                    
                     cn9.setText(fetch[57]);
                    cn10.setText(fetch[58]);
                    cn11.setText(fetch[59]);
                    cn12.setText(fetch[60]);
                    // mth.setText(fetch[19]);
                    // pr.setText(fetch[13]);
                    // bp.setText(fetch[11]);
                    String x = (fetch[3]);
                    //                          int len = x.length();
                    //                            char[] cc = x.toCharArray();
                    //                            for (int h = 0; h < len - 2; h = h + 3) {
                        //                                char temp = cc[h];
                        //                                cc[h] = cc[h + 2];
                        //                                cc[h + 2] = temp;
                        //                            }
                    //                             x = String.valueOf(cc);
                    String y = (fetch[4]);

                    //                         cc = y.toCharArray();
                    //                            for (int h = 0; h < len - 2; h = h + 3) {
                        //                                char temp = cc[h];
                        //                                cc[h] = cc[h + 2];
                        //                                cc[h + 2] = temp;
                        //                            }
                    //                             y= String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
                    //                    hd.setText(fetch[11]);
                    //                   String blood= (fetch[10]);
                    //                //   blood presure=
                    //                   String first="";
                    //                    int length = blood.length();
                    //        char[] ccx = blood.toCharArray();
                    //        for (int h = 0; h < 16; h = h + 1) {
                        //            first = first + ccx[h];
                        //        }
                    //
                    //                        bp.setText(first);
                    //
                    //                              String firsts="";
                    //        char[] ccxs = blood.toCharArray();
                    //        for (int h = 16; h < 36; h = h + 1) {
                        //            firsts = firsts + ccxs[h];
                        //        }
                    //
                    //                        rr.setText(firsts);
                    //
                    //
                    //                          String firstss="";
                    //        char[] ccxss = blood.toCharArray();
                    //        for (int h = 36; h < 50; h = h + 1) {
                        //            firstss = firstss + ccxs[h];
                        //        }
                    //
                    //                        pr.setText(firstss);
                    //
                    //                       String firstsss="";
                    //        char[] ccxsss = blood.toCharArray();
                    //        for (int h = 50; h < 64; h = h + 1) {
                        //            firstsss = firstsss + ccxss[h];
                        //        }
                    //
                    //                        tmp.setText(firstsss);

                    i++;
                }
                //                    JOptionPane.showMessageDialog(null, "SUCCESSFULL",
                    //                                              null,
                    //                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                    null,
                    JOptionPane.PLAIN_MESSAGE);
            }
            // }
        infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       new LOGIN().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pysical_examintion5("","","").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cn1;
    private javax.swing.JTextArea cn10;
    private javax.swing.JTextArea cn11;
    private javax.swing.JTextArea cn12;
    private javax.swing.JTextArea cn2;
    private javax.swing.JTextArea cn3;
    private javax.swing.JTextArea cn4;
    private javax.swing.JTextArea cn5;
    private javax.swing.JTextArea cn6;
    private javax.swing.JTextArea cn7;
    private javax.swing.JTextArea cn8;
    private javax.swing.JTextArea cn9;
    private javax.swing.JLabel display;
    private javax.swing.JLabel displayp;
    private javax.swing.JTextArea gls;
    private javax.swing.JTextField idfs;
    private javax.swing.JLabel infoid;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea mms;
    private javax.swing.JTextField pnm;
    private javax.swing.JButton rgbtn;
    // End of variables declaration//GEN-END:variables
}
