
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gech
 */
public class pysical_examintion2 extends javax.swing.JFrame {

    /**
     * Creates new form pysical_examintion2
     */
    public pysical_examintion2(String x, String y, String z) {
        initComponents();
        display.setText(x);
        displayp.setText(y);
        infoid.setText(z);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        insp = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        plp = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        prc = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        asc = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        inspc = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        pps = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        prcs = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        ascs = new javax.swing.JTextArea();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lgs = new javax.swing.JTextArea();
        pnm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        vns = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        art = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        idfs = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        regbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JLabel();
        displayp = new javax.swing.JLabel();
        infoid = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1112, 693));
        setPreferredSize(new java.awt.Dimension(1112, 693));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insp.setColumns(20);
        insp.setRows(5);
        jScrollPane1.setViewportView(insp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 293, 324, 50));

        plp.setColumns(20);
        plp.setRows(5);
        jScrollPane3.setViewportView(plp);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 361, 324, 50));

        prc.setColumns(20);
        prc.setRows(5);
        jScrollPane4.setViewportView(prc);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 417, 324, 50));

        asc.setColumns(20);
        asc.setRows(5);
        jScrollPane5.setViewportView(asc);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 473, 324, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("AUSCULTION");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 473, 130, 25));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("INSPECTION");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 259, 118, 25));

        inspc.setColumns(20);
        inspc.setRows(5);
        jScrollPane6.setViewportView(inspc);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 259, 324, 50));

        pps.setColumns(20);
        pps.setRows(5);
        jScrollPane7.setViewportView(pps);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 327, 324, 50));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("PALPOTION");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 327, 118, 25));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("AUSCULTION");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 486, 140, 25));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("PERCUTION");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 387, 118, 25));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("PRECORDIAL");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 233, 360, 20));

        prcs.setColumns(20);
        prcs.setRows(5);
        jScrollPane10.setViewportView(prcs);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 387, 324, 50));

        ascs.setColumns(20);
        ascs.setRows(5);
        jScrollPane11.setViewportView(ascs);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 478, 324, 50));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("PYSICAL EXAMINATION (P/E)");
        jLabel3.setBounds(140, 50, 299, 25);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("PATIENT NAME");
        jLabel17.setBounds(10, 130, 140, 29);
        jDesktopPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("ARTERIOL");
        jLabel18.setBounds(520, 100, 118, 30);
        jDesktopPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("RESPARATORY SYSTEM(RS)");
        jLabel6.setBounds(110, 230, 360, 17);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lgs.setColumns(20);
        lgs.setRows(5);
        jScrollPane2.setViewportView(lgs);

        jScrollPane2.setBounds(150, 170, 324, 50);
        jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnm.setBounds(150, 120, 326, 40);
        jDesktopPane1.add(pnm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("  LGS");
        jLabel4.setBounds(10, 170, 84, 25);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("LYMPHO GLANDULAR SYSTEM(LGS)");
        jLabel5.setBounds(70, 80, 360, 25);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        vns.setColumns(20);
        vns.setRows(5);
        jScrollPane13.setViewportView(vns);

        jScrollPane13.setBounds(650, 150, 324, 50);
        jDesktopPane1.add(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        art.setColumns(20);
        art.setRows(5);
        jScrollPane12.setViewportView(art);

        jScrollPane12.setBounds(650, 90, 324, 50);
        jDesktopPane1.add(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("VENOUS");
        jLabel19.setBounds(530, 150, 118, 25);
        jDesktopPane1.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("CARDIO VASCULAR SYSTEM(RS)");
        jLabel11.setBounds(610, 66, 360, 20);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("SEARCH FOR UPDATE ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(743, 13, 180, 40);
        jDesktopPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        idfs.setBounds(620, 20, 120, 30);
        jDesktopPane1.add(idfs, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("SKIP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(570, 510, 70, 40);
        jDesktopPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        regbtn.setText("SUBMIT");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });
        regbtn.setBounds(380, 510, 80, 40);
        jDesktopPane1.add(regbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("PERVIOUSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(260, 510, 110, 40);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("PERCUTION");
        jLabel9.setBounds(10, 390, 118, 25);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PALPOTION");
        jLabel7.setBounds(10, 340, 118, 25);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("INSPECTION");
        jLabel8.setBounds(10, 280, 118, 25);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanel1.setBounds(10, 10, 980, 550);
        jDesktopPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1000, 570));
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 120, 30));
        getContentPane().add(displayp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 130, 30));

        infoid.setText("jLabel1");
        getContentPane().add(infoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 644, 100, 30));

        jMenu1.setText("                                 LOGOUT ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new pysical_examintion(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new pysical_examintion3(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
        String lgss = lgs.getText();
        String inspection = insp.getText();
        String palpotion = plp.getText();
        String percution = prc.getText();
        String auscultation = asc.getText();
        String arteroi = art.getText();
        String venuos = vns.getText();

        String inspections = inspc.getText();
        String palpotions = pps.getText();
        String percutions = prcs.getText();
        String auscultations = ascs.getText();
        String precordial = "INSPECTION=" + inspections + "\nPALPOTION=" + palpotions + "\nPERCUTION=" + percutions + "\nAUSCULTATION=" + auscultations;
        String cardio_vascular_system = "ARTERIO=" + arteroi + "\nVENOUS=" + venuos;
        String resparatory_rate = "INSPECTION=" + inspection + "\nPALPOTION=" + palpotion + "\nPERCUTION=" + percution + "\nAUSCULTATION=" + auscultation;//insp.getText();
        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            System.out.println(hello.examination2(idfs.getText(),regbtn.getText(),arteroi, venuos, lgss, inspection, palpotion, percution, auscultation, inspections, palpotions, percutions, auscultations));
            JOptionPane.showMessageDialog(null, "CONTINUE",
                    null,
                    JOptionPane.PLAIN_MESSAGE);
            
            new pysical_examintion3(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);
        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }

    }//GEN-LAST:event_regbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1();
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                while (i < c) {
                    infoid.setText(fetch[0]);
                    //  gap.setText(fetch[9]);
                    String x = (fetch[3]);
//                          int len = x.length();
//                            char[] cc = x.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             x = String.valueOf(cc);
                    String y = (fetch[4]);

//                         cc = y.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             y= String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
//                    hd.setText(fetch[11]);
//                   String blood= (fetch[10]);
//                //   blood presure=
//                   String first="";
//                    int length = blood.length();
//        char[] ccx = blood.toCharArray();
//        for (int h = 0; h < 16; h = h + 1) {
//            first = first + ccx[h];
//        }
//                   
//                        bp.setText(first);
//                        
//                              String firsts="";
//        char[] ccxs = blood.toCharArray();
//        for (int h = 16; h < 36; h = h + 1) {
//            firsts = firsts + ccxs[h];
//        }
//                   
//                        rr.setText(firsts);
//                        
//                        
//                          String firstss="";
//        char[] ccxss = blood.toCharArray();
//        for (int h = 36; h < 50; h = h + 1) {
//            firstss = firstss + ccxs[h];
//        }
//                   
//                        pr.setText(firstss);
//                        
//                       String firstsss="";
//        char[] ccxsss = blood.toCharArray();
//        for (int h = 50; h < 64; h = h + 1) {
//            firstsss = firstsss + ccxss[h];
//        }
//                   
//                        tmp.setText(firstsss); 

                    i++;
                }
//                    JOptionPane.showMessageDialog(null, "SUCCESSFULL", 
//                                              null,
//                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                        null,
                        JOptionPane.PLAIN_MESSAGE);
            }
            // }
            infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }



    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1(idfs.getText());
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                if (regbtn.getText().equals("SUBMIT")) {
                    regbtn.setText("UPDATE");
                }

                while (i < c) {
                    infoid.setText(fetch[0]);

                    lgs.setText(fetch[20]);


                    insp.setText(fetch[21]);
                    plp.setText(fetch[22]);
                    prc.setText(fetch[23]);
                    asc.setText(fetch[24]);



                    inspc.setText(fetch[27]);
                    pps.setText(fetch[28]);
                    prcs.setText(fetch[29]);
                    ascs.setText(fetch[30]);

                    art.setText(fetch[25]);
                    vns.setText(fetch[26]);
                    // pr.setText(fetch[13]);
                    // bp.setText(fetch[11]);
                    String x = (fetch[3]);
//                          int len = x.length();
//                            char[] cc = x.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             x = String.valueOf(cc);
                    String y = (fetch[4]);

//                         cc = y.toCharArray();
//                            for (int h = 0; h < len - 2; h = h + 3) {
//                                char temp = cc[h];
//                                cc[h] = cc[h + 2];
//                                cc[h + 2] = temp;
//                            }
//                             y= String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
//                    hd.setText(fetch[11]);
//                   String blood= (fetch[10]);
//                //   blood presure=
//                   String first="";
//                    int length = blood.length();
//        char[] ccx = blood.toCharArray();
//        for (int h = 0; h < 16; h = h + 1) {
//            first = first + ccx[h];
//        }
//                   
//                        bp.setText(first);
//                        
//                              String firsts="";
//        char[] ccxs = blood.toCharArray();
//        for (int h = 16; h < 36; h = h + 1) {
//            firsts = firsts + ccxs[h];
//        }
//                   
//                        rr.setText(firsts);
//                        
//                        
//                          String firstss="";
//        char[] ccxss = blood.toCharArray();
//        for (int h = 36; h < 50; h = h + 1) {
//            firstss = firstss + ccxs[h];
//        }
//                   
//                        pr.setText(firstss);
//                        
//                       String firstsss="";
//        char[] ccxsss = blood.toCharArray();
//        for (int h = 50; h < 64; h = h + 1) {
//            firstsss = firstsss + ccxss[h];
//        }
//                   
//                        tmp.setText(firstsss); 

                    i++;
                }
//                    JOptionPane.showMessageDialog(null, "SUCCESSFULL", 
//                                              null,
//                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                        null,
                        JOptionPane.PLAIN_MESSAGE);
            }
            // }
            infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
     new LOGIN().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pysical_examintion2("", "", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea art;
    private javax.swing.JTextArea asc;
    private javax.swing.JTextArea ascs;
    private javax.swing.JLabel display;
    private javax.swing.JLabel displayp;
    private javax.swing.JTextField idfs;
    private javax.swing.JLabel infoid;
    private javax.swing.JTextArea insp;
    private javax.swing.JTextArea inspc;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea lgs;
    private javax.swing.JTextArea plp;
    private javax.swing.JTextField pnm;
    private javax.swing.JTextArea pps;
    private javax.swing.JTextArea prc;
    private javax.swing.JTextArea prcs;
    private javax.swing.JButton regbtn;
    private javax.swing.JTextArea vns;
    // End of variables declaration//GEN-END:variables
}
