
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gech
 */
public class pysical_examintion4 extends javax.swing.JFrame {

    /**
     * Creates new form pysical_examintion4
     */
    public pysical_examintion4(String x, String y, String z) {
        initComponents();
        display.setText(x);
        displayp.setText(y);
        infoid.setText(z);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        insp = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        plp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        insps = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        prc = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        plps = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        prcs = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ascs = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ausc = new javax.swing.JTextArea();
        pnm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        idfs = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rgbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        displayp = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        infoid = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1112, 693));
        setPreferredSize(new java.awt.Dimension(1112, 693));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("SKIP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        insp.setColumns(20);
        insp.setRows(5);
        jScrollPane1.setViewportView(insp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 324, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("MUSKOSKELETAL SYSTEM(MSK)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 360, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("PALPOTION");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 118, 30));

        plp.setColumns(20);
        plp.setRows(5);
        jScrollPane3.setViewportView(plp);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 324, 50));

        insps.setColumns(20);
        insps.setRows(5);
        jScrollPane2.setViewportView(insps);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 150, 320, 50));

        prc.setColumns(20);
        prc.setRows(5);
        jScrollPane4.setViewportView(prc);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 324, 50));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("INSPECTION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, 25));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("PERCUTION");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 118, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("INTEGMENTARY SYSTEM(SKIN)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 360, 40));

        plps.setColumns(20);
        plps.setRows(5);
        jScrollPane8.setViewportView(plps);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 324, 50));

        prcs.setColumns(20);
        prcs.setRows(5);
        jScrollPane7.setViewportView(prcs);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 324, 50));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("INSPECTION");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 118, 25));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("PERCUTION");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 118, 25));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PALPOTION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 118, 25));

        ascs.setColumns(20);
        ascs.setRows(5);
        jScrollPane6.setViewportView(ascs);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 324, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("AUSCULTION");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, 25));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("AUSCULTION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 130, 25));

        ausc.setColumns(20);
        ausc.setRows(5);
        jScrollPane5.setViewportView(ausc);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 324, 50));
        getContentPane().add(pnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 326, 40));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("PATIENT AME");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, 29));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.add(idfs);
        idfs.setBounds(520, 20, 180, 40);

        jButton5.setText("SEARCH FOR UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(720, 20, 170, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("PERVIOUSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(200, 410, 135, 31);

        rgbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rgbtn.setText("REGISTER");
        rgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(rgbtn);
        rgbtn.setBounds(360, 410, 123, 31);
        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(10, 10, 970, 520);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 990, 540));
        getContentPane().add(displayp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 130, 30));
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 120, 30));

        infoid.setText("jLabel1");
        getContentPane().add(infoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 594, 100, 30));

        jMenu1.setText("                                                      LOGOUT ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new pysical_examintion3(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new pysical_examintion5(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgbtnActionPerformed
        String inspection = insp.getText();
        String palpotion = plp.getText();
        String percution = prc.getText();
        String auscultation = ausc.getText();

        String inspections = insps.getText();
        String palpotions = plps.getText();
        String percutions = prcs.getText();
        String auscultations = ascs.getText();

        String integmentary_system = "INSPECTION=" + inspections + "\nPALPOTION=" + inspections + "\nPERCUTION=" + percutions + "\nAUSCULTATION=" + auscultations;
        //String cardio_vascular_system="ARTERIO="+arteroi+"\nVENOUS="+venuos;
        String musko_skeletal_system = "INSPECTION=" + inspection + "\nPALPOTION=" + palpotion + "\nPERCUTION=" + percution + "\nAUSCULTATION=" + auscultation;//insp.getText();
        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            System.out.println(hello.examination4(idfs.getText(),rgbtn.getText(),inspection,palpotion,percution,auscultation, inspections,palpotions,percutions,auscultations));
            JOptionPane.showMessageDialog(null, "CONTINUE",
                    null,
                    JOptionPane.PLAIN_MESSAGE);
             new pysical_examintion5(display.getText(), displayp.getText(), infoid.getText()).setVisible(true);
        this.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }

    }//GEN-LAST:event_rgbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1();
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                while (i < c) {
                    infoid.setText(fetch[0]);
                    //  gap.setText(fetch[9]);
                    String x = (fetch[3]);
                    int len = x.length();
                    char[] cc = x.toCharArray();
                    for (int h = 0; h < len - 2; h = h + 3) {
                        char temp = cc[h];
                        cc[h] = cc[h + 2];
                        cc[h + 2] = temp;
                    }
                    x = String.valueOf(cc);
                    String y = (fetch[4]);

                    cc = y.toCharArray();
                    for (int h = 0; h < len - 2; h = h + 3) {
                        char temp = cc[h];
                        cc[h] = cc[h + 2];
                        cc[h + 2] = temp;
                    }
                    y = String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
//                    hd.setText(fetch[11]);
//                   String blood= (fetch[10]);
//                //   blood presure=
//                   String first="";
//                    int length = blood.length();
//        char[] ccx = blood.toCharArray();
//        for (int h = 0; h < 16; h = h + 1) {
//            first = first + ccx[h];
//        }
//                   
//                        bp.setText(first);
//                        
//                              String firsts="";
//        char[] ccxs = blood.toCharArray();
//        for (int h = 16; h < 36; h = h + 1) {
//            firsts = firsts + ccxs[h];
//        }
//                   
//                        rr.setText(firsts);
//                        
//                        
//                          String firstss="";
//        char[] ccxss = blood.toCharArray();
//        for (int h = 36; h < 50; h = h + 1) {
//            firstss = firstss + ccxs[h];
//        }
//                   
//                        pr.setText(firstss);
//                        
//                       String firstsss="";
//        char[] ccxsss = blood.toCharArray();
//        for (int h = 50; h < 64; h = h + 1) {
//            firstsss = firstsss + ccxss[h];
//        }
//                   
//                        tmp.setText(firstsss); 

                    i++;
                }
//                    JOptionPane.showMessageDialog(null, "SUCCESSFULL", 
//                                              null,
//                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                        null,
                        JOptionPane.PLAIN_MESSAGE);
            }
            // }
            infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");

            String fetch[] = new String[5000];
            fetch = hello.Update_examination1(idfs.getText());
            int c = fetch.length;
            int i = 0, j = 0, idx = 0;
            if (c >= 1) {
                if(rgbtn.getText().equals("REGISTER"))
                {
                    rgbtn.setText("UPDATE");
                }

                while (i < c) {
                    infoid.setText(fetch[0]);

                    insp.setText(fetch[39]);
                    plp.setText(fetch[40]);
                    prc.setText(fetch[41]);
                    ausc.setText(fetch[42]);
                    // tmp.setText(fetch[14]);

                    insps.setText(fetch[43]);
                    plps.setText(fetch[44]);
                    prcs.setText(fetch[45]);
                    ascs.setText(fetch[46]);
                    // mth.setText(fetch[19]);
                    // pr.setText(fetch[13]);
                    // bp.setText(fetch[11]);
                    String x = (fetch[3]);
                    //                          int len = x.length();
                    //                            char[] cc = x.toCharArray();
                    //                            for (int h = 0; h < len - 2; h = h + 3) {
                        //                                char temp = cc[h];
                        //                                cc[h] = cc[h + 2];
                        //                                cc[h + 2] = temp;
                        //                            }
                    //                             x = String.valueOf(cc);
                    String y = (fetch[4]);

                    //                         cc = y.toCharArray();
                    //                            for (int h = 0; h < len - 2; h = h + 3) {
                        //                                char temp = cc[h];
                        //                                cc[h] = cc[h + 2];
                        //                                cc[h + 2] = temp;
                        //                            }
                    //                             y= String.valueOf(cc);
                    String z = x + "   " + y;
                    pnm.setText(z);
                    //                    hd.setText(fetch[11]);
                    //                   String blood= (fetch[10]);
                    //                //   blood presure=
                    //                   String first="";
                    //                    int length = blood.length();
                    //        char[] ccx = blood.toCharArray();
                    //        for (int h = 0; h < 16; h = h + 1) {
                        //            first = first + ccx[h];
                        //        }
                    //
                    //                        bp.setText(first);
                    //
                    //                              String firsts="";
                    //        char[] ccxs = blood.toCharArray();
                    //        for (int h = 16; h < 36; h = h + 1) {
                        //            firsts = firsts + ccxs[h];
                        //        }
                    //
                    //                        rr.setText(firsts);
                    //
                    //
                    //                          String firstss="";
                    //        char[] ccxss = blood.toCharArray();
                    //        for (int h = 36; h < 50; h = h + 1) {
                        //            firstss = firstss + ccxs[h];
                        //        }
                    //
                    //                        pr.setText(firstss);
                    //
                    //                       String firstsss="";
                    //        char[] ccxsss = blood.toCharArray();
                    //        for (int h = 50; h < 64; h = h + 1) {
                        //            firstsss = firstsss + ccxss[h];
                        //        }
                    //
                    //                        tmp.setText(firstsss);

                    i++;
                }
                //                    JOptionPane.showMessageDialog(null, "SUCCESSFULL",
                    //                                              null,
                    //                                              JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EMPTY",
                    null,
                    JOptionPane.PLAIN_MESSAGE);
            }
            // }
        infoid.setVisible(false);

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
            // lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
       new LOGIN().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pysical_examintion4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pysical_examintion4("", "", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ascs;
    private javax.swing.JTextArea ausc;
    private javax.swing.JLabel display;
    private javax.swing.JLabel displayp;
    private javax.swing.JTextField idfs;
    private javax.swing.JLabel infoid;
    private javax.swing.JTextArea insp;
    private javax.swing.JTextArea insps;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea plp;
    private javax.swing.JTextArea plps;
    private javax.swing.JTextField pnm;
    private javax.swing.JTextArea prc;
    private javax.swing.JTextArea prcs;
    private javax.swing.JButton rgbtn;
    // End of variables declaration//GEN-END:variables
}
