
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.event.KeyEvent;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gech
 */
public class Sickleave extends javax.swing.JFrame {

    /**
     * Creates new form Sickleave
     */
    public Sickleave(String x, String y, String z) {
        initComponents();
        display.setText(x);
        displayp.setText(y);
        id.setText(z);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayp = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sp = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        fn = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rx = new javax.swing.JTextField();
        sc = new javax.swing.JTextField();
        rc = new javax.swing.JTextField();
        idt = new javax.swing.JLabel();
        pnm = new javax.swing.JLabel();
        dip = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1112, 693));
        setPreferredSize(new java.awt.Dimension(1112, 693));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("MEDICAL CERTEFICATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 299, 25));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 105, 123, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("G/U:- ATSE TEWODROS STUDENT'S CLINIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 400, 25));
        getContentPane().add(displayp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 130, 30));
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 120, 30));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("SAVE ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(260, 420, 80, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText(" SEX");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(30, 290, 174, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText(" LAST NAME");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(30, 250, 174, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText(" FIRST NAME");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(30, 190, 174, 25);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText(" DATE OF CLINIC VISIT");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(30, 150, 174, 25);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText(" ID NUMBER");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(30, 110, 174, 25);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });
        sp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spKeyTyped(evt);
            }
        });
        jPanel1.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 180, 40));

        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 180, 30));
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, 30));
        jPanel1.add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 180, 30));
        jPanel1.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(" Rx GIVEN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 130, 25));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText(" SICK LEAVE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, 25));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("RECOMENDATION");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, 25));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText(" DATE OF ISSUE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 130, 25));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText(" PHYSICIAN NAME");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 140, 25));

        rx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rxActionPerformed(evt);
            }
        });
        jPanel1.add(rx, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 180, 30));
        jPanel1.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 180, 30));
        jPanel1.add(rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 180, 30));
        jPanel1.add(idt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 180, 30));

        pnm.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 180, 30));

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(10, 10, 810, 480);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 830, 500));
        getContentPane().add(dip, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 574, 130, 30));

        jMenu1.setText("BACK                   ");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("LOGOUT                      ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SimpleDateFormat sdfs = new SimpleDateFormat("yyyy-MM-dd");
        //String date=sp.getValue().toString();
//        String FormattedDate=sdfs.format(sp.getValue());
//        dip.setText(FormattedDate);





        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        String x = s.format(d);
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String time = sdf.format(d);









        try {
            RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");
            String fetch[] = new String[5000];

            if (id.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER ID NUMBER",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
            } else if ((id.getText().length() < 7) || (id.getText().length() > 7)) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VALID SIZE OF ID NUMBER",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                id.setText("");
            } else if (sp.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VISITED DATE",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
            } else if ((sp.getText().length() < 10) || (sp.getText().length() > 10)) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VALID SIZE OF VISITED DATE",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                sp.setText("");
            }
            String dx = sp.getText();
            int cn = 0;
            String fivith_letter = null;
            int length = dx.length();
            char[] ccx = dx.toCharArray();
            for (int h = 4; h <= 4; h = h + 1) {
                fivith_letter = "" + ccx[h];
            }
            String eighth_letter = null;
            int lengthss = dx.length();
            char[] ccxss = dx.toCharArray();
            for (int h = 7; h <= 7; h = h + 1) {
                eighth_letter = "" + ccxss[h];
            }


            System.out.println(fivith_letter + "\n" + eighth_letter);
            if (!(fivith_letter.equals("-")) || !(eighth_letter.equals("-"))) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER CORRECT DATE FORMAT\n DATE FORMAT MUST BE\n yyyy-mm-dd LIKE 2017-06-25",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                sp.setText("");
            } else {
                fetch = hello.print_sickleave(id.getText(), sp.getText());
                int c = fetch.length;
                int i = 0, j = 0, idx = 0;
                if (c >= 1) {
                    while (i < c) {
                        id.setText(fetch[1]);
                        fn.setText(fetch[3]);
                        mn.setText(fetch[4]);
                        sex.setText(fetch[5]);
                        idt.setText(x);
                        pnm.setText(display.getText());
                        i++;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "THIS ID NUMBER IS NOT EXIST IN HISTORY",
                            null,
                            JOptionPane.PLAIN_MESSAGE);
                }
            }

        } catch (NotBoundException e) {
            System.out.println("Clinicalclient not bound exception:" + e);
        } catch (Exception e) {
            System.out.println("HelloClient exception:" + e);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        String x = s.format(d);
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String time = sdf.format(d);


        try {
            Mainclass ob = new Mainclass();
            ob.id_number = id.getText();
            ob.first_name = fn.getText();
            ob.middle_name = mn.getText();
            ob.sex = sex.getText();
            ob.rx_given = rx.getText();
            String sickleave = sc.getText();
            String recomendation = rc.getText();
            String date_issue = x;
            String physican_name = pnm.getText();
            String visited_date = sp.getText();
            if (ob.id_number.isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER ID NUMBER",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                id.setBorder(null);
                id.setHighlighter(null);
            } else if ((id.getText().length() < 7) || (id.getText().length() > 7)) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VALID SIZE OF ID NUMBER",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                id.setBorder(null);
                id.setHighlighter(null);
                id.setText("");
            } else if (fn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER FIRST NAME",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
            } else if ((fn.getText().length() < 3) || (fn.getText().length() > 15)) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VALID SIZE OF FIRST NAME",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                fn.setText("");
            } else if (mn.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER MIDDLE NAME",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
            } else if ((mn.getText().length() < 3) || (mn.getText().length() > 15)) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER VALID SIZE OF MIDDLE NAME",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                mn.setText("");
            } else if (rx.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER HISTORY GIVEN",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
            } else if (sc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER SICK LEAVE",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                sc.setText("");
            } else if (rc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "PLEASE ENTER RECOMENDATION",
                        null,
                        JOptionPane.QUESTION_MESSAGE);
                rc.setText("");
            } else {
                try {
                    RMIInterface hello = (RMIInterface) Naming.lookup("//localhost/clinical");
                    int YesorNo = JOptionPane.showConfirmDialog(null, "DO U WANT TO SAVE", "sava button", JOptionPane.YES_NO_OPTION);
                    if (YesorNo == 0) {
                        System.out.println(hello.save_sickleave("1", x, ob.id_number, ob.first_name, ob.middle_name, ob.sex, ob.rx_given, sickleave, recomendation, date_issue, physican_name, visited_date));
                        JOptionPane.showMessageDialog(null, "SICK LEAVE IS SUCCESSFULLY PREPARED DO U WANT TO PRINT",
                                null,
                                JOptionPane.PLAIN_MESSAGE);

                        new print_sickleave(display.getText(), displayp.getText(), id.getText()).setVisible(true);
                        this.setVisible(false);
                    }

                } catch (NotBoundException e) {
                    //System.out.println("Clinicalclient not bound exception:" +e);
                    JOptionPane.showMessageDialog(null, "Clinicalclient not bound exception:" + e,
                            null,
                            JOptionPane.PLAIN_MESSAGE);
                    JOptionPane.showMessageDialog(null, "Clinicalclient not bound exception:" + e.getMessage(),
                            null,
                            JOptionPane.PLAIN_MESSAGE);
                    //  lbl.setText("Clinicalclient not bound exception:" +e.getMessage());
                } catch (Exception e) {
                    System.out.println("HelloClient exception:" + e);
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Register_pat_info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        dip.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spActionPerformed

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
    }//GEN-LAST:event_idMouseClicked

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                || c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_SLASH) || (c == KeyEvent.VK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "id number must be number",
                    null,
                    JOptionPane.QUESTION_MESSAGE);
            //gettoolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_idKeyTyped

    private void spKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                || c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER) || (c == KeyEvent.VK_MINUS) || (c == KeyEvent.VK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(null, "date is allowed only number and - in between",
                    null,
                    JOptionPane.QUESTION_MESSAGE);
            //gettoolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_spKeyTyped

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new Doctor(display.getText(), displayp.getText()).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       new LOGIN().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void rxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rxActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sickleave.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sickleave.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sickleave.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sickleave.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sickleave("", "", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dip;
    private javax.swing.JLabel display;
    private javax.swing.JLabel displayp;
    private javax.swing.JLabel fn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel pnm;
    private javax.swing.JTextField rc;
    private javax.swing.JTextField rx;
    private javax.swing.JTextField sc;
    private javax.swing.JLabel sex;
    private javax.swing.JTextField sp;
    // End of variables declaration//GEN-END:variables
}
